name: Rust Release (Linux Musl)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target:
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-musl

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust for Target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Set Git User
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Create Release
        run: |
          git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
          git push origin v${{ github.run_number }}

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/${{ matrix.target }}/release/rust_socks_server

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/rust_socks_server
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Release notes for v${{ github.run_number }}"
